<div class="d-flex justify-content-evenly">

    <div class="col-lg-3 col-md-6">
        <div class="footer-info">
            <h3>Đi Chợ Thuê</h3>
            <p>
                ĐH KHTN <br>
                Nguyễn Văn Cừ, Q5<br><br>
                <strong>Phone:</strong> 123456789 <br>
                <strong>Email:</strong> tranhuuhoanghcmus.com<br>
            </p>
        </div>
    </div>

    <div class="col-lg-3 col-md-6 footer-links">
        <h4>Các liên kết</h4>
        <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Trang chủ</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Về chúng tôi</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Các dịch vụ</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Điều khoản dịch vụ</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="#">Chính sách riêng tư</a></li>
        </ul>
    </div>
    <div class="col-lg-4 col-md-6 footer-newsletter">
        <h4>Về Chúng Tôi</h4>
        <p>Ứng dụng hỗ trợ khách hàng đi chợ bằng phương pháp trực tuyến</p>
    </div>
</div>

<div>
    <div>
        &copy; Copyright 2022 <strong><span>UDPT</span></strong>. All Rights Reserved. Developed by <strong><span>Nhóm
                Six</span></strong>
    </div>
</div>