<div class="container">
    <!-- <div>
        <?php echo $result->name?>
    </div> -->
    <!-- <div>
        <?php print_r($result);?>
    </div> -->
    <div class="d-flex justify-content-center">
        <div>
            <h4 class="text-center">Thông tin tài khoản cửa hàng <?php echo $result->name?></h4>
            <div>
                <img src="$result->logo" alt="logo" />
            </div>
            <form class="was-validated mb-3" method="post">
                <div class="row">
                    <div class="col-md-6">
                        <label for="inputName">Tên cửa hàng (*)</label>
                        <input value="<?=$result->name?>" type="input" class="form-control" id="inputName" name="name"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                    <div class="col-md-6">
                        <label for="inputBirtDay">Ngày mở(*)</label>
                        <input value="<?=$result->dayStart?>" type="datetime-local" class="form-control" id="birtd"
                            name="dayStart" oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-md-6">
                        <label for="inputName">Giờ mở cửa(*)</label>
                        <input value="<?=$result->timeOpen?>" type="time" class="form-control" name="timeOpen"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                    <div class="col-md-6">
                        <label for="inputBirtDay">Giờ đóng cửa(*)</label>
                        <input value="<?=$result->timeClose?>" type="time" class="form-control"
                            name="timeClose" oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-md-12">
                        <label for="inputNameFamily">Loại sản phẩm kinh doanh (*)</label>
                        <input value="<?=$result->productCategory?>" type="input" class="form-control"
                            name="productCategory" oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-md-6">
                        <label for="inputCustomer">Số điện thoại (*)</label>
                        <input value="<?=$result->phone?>" type="input" class="form-control" id="customerID"
                            name="phone" oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="inputAddress">Trạng thái (*)</label>
                            <div class="custom-control custom-radio from-check">
                                
                                    <?php 
                                    if($result->active == 0){ 
                                        echo '<label class="custom-control-label text-warning">Chưa kích hoạt</label>';
                                    }else{
                                        echo '<label class="custom-control-label text-success">Đã kích hoạt tài khoản</label>';
                                    } 
                                    ?>
                                
                            </div>
                        </div>
                    </div>
                </div><br />
                <!-- {{!-- province, district, ward --}} -->
                <div class="row">
                    <div class="col-md-4">
                        <label for="inputCity">Tỉnh thành (*)</label>
                        <select class="form-select" id="citySelect" onchange="choosedCity()" name="province"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                            <option value="<?=$result->province?>">
                                <?=$result->province?>
                            </option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="inputDistrict">Quận huyện (*)</label>
                        <select class="form-select" id="district" onchange="choosedDistrict()" name="district"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                            <option value="<?=$result->district?>">
                                <?=$result->district?>
                            </option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="inputWard">Phường xã (*)</label>
                        <select class="form-select" id="ward" name="ward"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                            <option value="<?=$result->ward?>">
                                <?=$result->ward?>
                            </option>
                        </select>
                    </div>
                </div><br />
                <!-- {{!-- address --}} -->
                <div class="row">
                    <div class="col-md-12">
                        <label for="inputStreet">Số nhà, tên đường (*)</label>
                        <input value="<?=$result->address?>" type="input" class="form-control" id="street"
                            name="address" oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                </div><br />
                <!-- {{!-- email --}} -->
                <div class="row">
                    <div class="col-md-12">
                        <label for="inputNameFamily">Email (*)</label>
                        <input value="<?=$result->email?>" type="input" class="form-control" id="nameFamily"
                            name="email" oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                </div><br />
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-success">Cập Nhật Thông Tin</button>
                </div>
            </form>
            <div class="pt-5 mt-5 border-top border-primary">
                <form action="" method="post">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="inputPassword">Mật khẩu (*)</label>
                            <input type="password" class="form-control" id="password" name="password"
                                oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                                onchange="this.setCustomValidity('')" required>
                        </div>
                        <div class="col-md-6">
                            <label for="inputPassword">Xác nhận mật khẩu (*)</label>
                            <input type="password" class="form-control" id="confirm_password" name="repassword" required>
                        </div>
                    </div><br />
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-success">Đổi mật khẩu</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    var locationVN = null;
    var cityCustomer = null;
    window.onload = function () {
        (async () => {
            locationVN = await fetch('https://provinces.open-api.vn/api/?depth=3')
                .then(res => { return res.json() });
            pushCityInputBox();
        })();
    };

    function pushCityInputBox() {
        let provincesNameHTML = `<option value="">Chọn tỉnh thành</option>`;
        for (province of locationVN) {
            provincesNameHTML += `<option value="${province.name}">${province.name}</option>`;
        }
        document.getElementById("citySelect").innerHTML += provincesNameHTML;
    }

    function choosedCity() {
        document.getElementById("district").innerHTML = "";
        document.getElementById("district").value = "";
        document.getElementById("ward").innerHTML = "";
        document.getElementById("ward").value = "";
        let nameCity = document.getElementById("citySelect").value;
        cityCustomer = locationVN.filter(item => item.name == nameCity)[0];
        let districtsHTML = "";
        for (let district of cityCustomer.districts) {
            districtsHTML += `<option value="${district.name}">${district.name}</option>`;
        };
        document.getElementById("district").innerHTML = districtsHTML;
    }

    function choosedDistrict() {
        let nameDistrict = document.getElementById("district").value;
        let wards = cityCustomer.districts.filter(item => item.name == nameDistrict)
        let wardsHTML = ""
        for (let ward of wards[0].wards) {
            wardsHTML += `<option value="${ward.name}">${ward.name}</option>`
        }
        document.getElementById("ward").innerHTML = wardsHTML
    }

    var password = document.getElementById("password");
    var confirm_password = document.getElementById("confirm_password");

    function validatePassword() {
        if (password.value != confirm_password.value) {
            confirm_password.setCustomValidity("Không khớp mật khẩu!");
        } else {
            confirm_password.setCustomValidity('');
        }
    }

    password.onchange = validatePassword;
    confirm_password.onkeyup = validatePassword;

    $(window).on('load', function () {
        $('#warningRelPersonModal').modal('show');
    });
    $(document).ready(() => {
        $('#hideNoticeRelPerson').click(() => {
            $('#warningRelPersonModal').modal('hide');
        })
    })
</script>