<div class="container">
    <div class="d-flex justify-content-center">
        <div>
            <h4 class="text-center">Đăng ký tài khoản</h4>
            <form class="was-validated mb-3" method="post">
                <div class="row">
                    <div class="col-md-6">
                        <label for="inputName">Họ tên (*)</label>
                        <input value="{{customer.name}}" type="input" class="form-control" id="inputName" name="name"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                    <div class="col-md-6">
                        <label for="inputBirtDay">Ngày sinh(*)</label>
                        <input value="{{customer.birth}}" defaultValue="{{customer.birth}}" type="datetime-local" class="form-control" id="birtd" name="birth"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-md-6">
                        <label for="inputCustomer">Số điện thoại (*)</label>
                        <input value="{{customer.phone}}" type="input" class="form-control" id="customerID" name="phone"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                        <div class="invalid-feedback">Vui lòng điền thông tin.</div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="inputAddress">Giới tính (*)</label>
                            <div class="custom-control custom-radio from-check">
                                <input {{#if (isMale customer.sex)}}checked="checked"{{else}}{{/if}}
                                    type="radio" class="custom-control-input form-check-input"
                                    id="customControlValidation2" value="M" name="sex"
                                    oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                                    onchange="this.setCustomValidity('')" required>
                                <label class="custom-control-label" for="customControlValidation2">Nam</label>
                            </div>
                            <div class="custom-control custom-radio mb-3">
                                <input {{#if (isMale customer.sex)}}{{else}}checked="checked"{{/if}}
                                    type="radio" class="custom-control-input form-check-input"
                                    id="customControlValidation3" value="F" name="sex" required>
                                <label class="custom-control-label" for="customControlValidation3">Nữ</label>
                            </div>
                        </div>
                    </div>
                </div><br />
                {{!-- province, district, ward --}}
                <div class="row">
                    <div class="col-md-4">
                        <label for="inputCity">Tỉnh thành (*)</label>
                        <select class="form-select" id="citySelect" onchange="choosedCity()" name="province"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                            <option value="{{customer.address.province}}">{{customer.address.province}}</option>
                            {{#each locations}}
                            <option value="{{this.name}}">{{this.name}}</option>
                            {{/each}}
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="inputDistrict">Quận huyện (*)</label>
                        <select class="form-select" id="district" onchange="choosedDistrict()" name="district"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                            <option value="{{customer.address.district}}">{{customer.address.district}}</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="inputWard">Phường xã (*)</label>
                        <select class="form-select" id="ward" name="ward"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                            <option value="{{customer.address.ward}}">{{customer.address.ward}}</option>
                        </select>
                    </div>
                </div><br />
                {{!-- address --}}
                <div class="row">
                    <div class="col-md-12">
                        <label for="inputStreet">Số nhà, tên đường (*)</label>
                        <input value="{{customer.address.address}}"
                            type="input" class="form-control" id="street" name="address"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                </div><br />
                {{!-- email --}}
                <div class="row">
                    <div class="col-md-12">
                        <label for="inputNameFamily">Email (*)</label>
                        <input value="{{customer.email}}"
                            type="input" class="form-control" id="nameFamily" name="email"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                </div><br />
                {{!-- password --}}
                <div class="row">
                    <div class="col-md-6">
                        <label for="inputPassword">Mật khẩu (*)</label>
                        <input type="password" class="form-control" id="password" name="password"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                    <div class="col-md-6">
                        <label for="inputPassword">Xác nhận mật khẩu (*)</label>
                        <input type="password" class="form-control" id="confirm_password" name="repassword" required>
                    </div>
                </div><br />
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-success">Cập Nhật Thông Tin</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var locationVN = null;
    var cityCustomer = null;
    window.onload = function () {
        (async () => {
            locationVN = await fetch('https://provinces.open-api.vn/api/?depth=3')
                .then(res => {return res.json()});
        })();
    };

    function choosedCity() {
        document.getElementById("district").innerHTML = "";
        document.getElementById("district").value = "";
        document.getElementById("ward").innerHTML = "";
        document.getElementById("ward").value="";
        let nameCity = document.getElementById("citySelect").value;
        cityCustomer = locationVN.filter(item => item.name == nameCity)[0];
        let districtsHTML = "";
        for (let district of cityCustomer.districts) {
            districtsHTML += `<option value="${district.name}">${district.name}</option>`;
        };
         document.getElementById("district").innerHTML= districtsHTML;
    }

    function choosedDistrict() {
        let nameDistrict = document.getElementById("district").value;
        let wards = cityCustomer.districts.filter(item => item.name == nameDistrict)
        let wardsHTML = ""
        for (let ward of wards[0].wards) {
            wardsHTML += `<option value="${ward.name}">${ward.name}</option>`
        }
        document.getElementById("ward").innerHTML = wardsHTML
    }

    var password = document.getElementById("password");
    var confirm_password = document.getElementById("confirm_password");

    function validatePassword() {
        if (password.value != confirm_password.value) {
            confirm_password.setCustomValidity("Không khớp mật khẩu!");
        } else {
            confirm_password.setCustomValidity('');
        }
    }

    password.onchange = validatePassword;
    confirm_password.onkeyup = validatePassword;
</script>